# Generated by Django 5.2.3 on 2025-07-15 01:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('courses', '0001_initial'),
        ('teachers', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='schedule',
            name='teacher',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='teachers.teacher'),
        ),
        migrations.AddField(
            model_name='schedule',
            name='subject',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='courses.subject'),
        ),
        migrations.AddField(
            model_name='course',
            name='subjects',
            field=models.ManyToManyField(related_name='courses', to='courses.subject'),
        ),
        migrations.AlterUniqueTogether(
            name='schedule',
            unique_together={('teacher', 'day_of_week', 'start_time')},
        ),
        migrations.AlterUniqueTogether(
            name='course',
            unique_together={('grade', 'semester')},
        ),
    ]
